[package]
name = "rakhas_logger"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
chrono-tz = "0.10.4"
colorize = "0.1.0"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["full"] }
